package kernel

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	// PayloadZipRel is the go:embed input regenerated by Sync.
	PayloadZipRel = "internal/kernel/payload/kernel.zip"
)

func manifestBytes(m *Manifest) ([]byte, error) {
	raw, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(raw, '\n'), nil
}

// packagedManifest returns a copy suitable for the embed zip: volatile
// generated_at is cleared so identical source trees produce identical payload bytes.
func packagedManifest(m *Manifest) *Manifest {
	files := make(map[string]string, len(m.Files))
	for k, v := range m.Files {
		files[k] = v
	}
	return &Manifest{
		Version: m.Version,
		Files:   files,
	}
}

// writePayloadZip builds a zip of allowlisted sources + packaged manifest.json for go:embed.
func writePayloadZip(repoRoot string, entries []SourceEntry, m *Manifest) (string, error) {
	byDest := make(map[string]string, len(entries))
	paths := make([]string, 0, len(entries)+1)
	for _, e := range entries {
		paths = append(paths, e.Dest)
		byDest[e.Dest] = e.Source
	}
	paths = append(paths, "manifest.json")
	sort.Strings(paths)

	packaged := packagedManifest(m)
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, rel := range paths {
		var raw []byte
		var err error
		if rel == "manifest.json" {
			raw, err = manifestBytes(packaged)
		} else {
			rawSrc, ok := byDest[rel]
			if !ok {
				_ = zw.Close()
				return "", fmt.Errorf("payload: missing source for %s", rel)
			}
			src := filepath.Join(repoRoot, filepath.FromSlash(rawSrc))
			raw, err = os.ReadFile(src)
		}
		if err != nil {
			_ = zw.Close()
			return "", err
		}
		w, err := zw.CreateHeader(&zip.FileHeader{
			Name:   rel,
			Method: zip.Deflate,
		})
		if err != nil {
			_ = zw.Close()
			return "", err
		}
		if _, err := w.Write(raw); err != nil {
			_ = zw.Close()
			return "", err
		}
	}
	if err := zw.Close(); err != nil {
		return "", err
	}

	out := filepath.Join(repoRoot, filepath.FromSlash(PayloadZipRel))
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return "", err
	}
	tmp := out + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmp, out); err != nil {
		_ = os.Remove(tmp)
		return "", err
	}
	sum := sha256.Sum256(buf.Bytes())
	return hex.EncodeToString(sum[:]), nil
}

func verifyPayloadZip(repoRoot string, entries []SourceEntry, m *Manifest) []Drift {
	zipPath := filepath.Join(repoRoot, filepath.FromSlash(PayloadZipRel))
	raw, err := os.ReadFile(zipPath)
	if err != nil {
		return []Drift{{Path: PayloadZipRel, Reason: "missing embed payload zip"}}
	}
	return verifyZipBytes(raw, entries, m, PayloadZipRel)
}

func verifyZipBytes(raw []byte, entries []SourceEntry, m *Manifest, label string) []Drift {
	zr, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		return []Drift{{Path: label, Reason: "unreadable zip: " + err.Error()}}
	}
	want := map[string]string{}
	for _, e := range entries {
		want[e.Dest] = m.Files[e.Dest]
	}
	manRaw, err := manifestBytes(packagedManifest(m))
	if err != nil {
		return []Drift{{Path: label, Reason: "manifest marshal failed"}}
	}
	h := sha256.Sum256(manRaw)
	want["manifest.json"] = hex.EncodeToString(h[:])

	var drifts []Drift
	seen := map[string]bool{}
	for _, f := range zr.File {
		name := filepath.ToSlash(f.Name)
		seen[name] = true
		rc, err := f.Open()
		if err != nil {
			drifts = append(drifts, Drift{Path: name, Reason: "zip entry unreadable"})
			continue
		}
		body, err := io.ReadAll(rc)
		_ = rc.Close()
		if err != nil {
			drifts = append(drifts, Drift{Path: name, Reason: "zip entry read failed"})
			continue
		}
		sum := sha256.Sum256(body)
		got := hex.EncodeToString(sum[:])
		exp, ok := want[name]
		if !ok {
			drifts = append(drifts, Drift{Path: name, Reason: "extra file in payload zip"})
			continue
		}
		if got != exp {
			drifts = append(drifts, Drift{Path: name, Reason: "payload zip digest mismatch", Want: shortDigest(exp), Got: shortDigest(got)})
		}
	}
	for name := range want {
		if !seen[name] {
			drifts = append(drifts, Drift{Path: name, Reason: "missing from payload zip"})
		}
	}
	sort.Slice(drifts, func(i, j int) bool { return drifts[i].Path < drifts[j].Path })
	return drifts
}

// InstallOptions controls kernel payload extraction into a consumer repo.
type InstallOptions struct {
	Force bool
}

// joinUnderTarget resolves name under target and rejects path escape
// (absolute names, Windows volumes, ".." segments, or cleaned paths leaving the tree).
func joinUnderTarget(target, name string) (string, error) {
	name = filepath.ToSlash(strings.TrimSpace(name))
	if name == "" {
		return "", fmt.Errorf("kernel install: empty zip entry name")
	}
	// Slash-rooted and Windows volume/drive-relative names (reject on every GOOS).
	if strings.HasPrefix(name, "/") || windowsVolumePrefix(name) {
		return "", fmt.Errorf("kernel install: absolute zip entry rejected: %s", name)
	}
	rel := filepath.FromSlash(name)
	if filepath.IsAbs(rel) || filepath.VolumeName(rel) != "" {
		return "", fmt.Errorf("kernel install: absolute zip entry rejected: %s", name)
	}
	cleaned := filepath.Clean(rel)
	if cleaned == "." || cleaned == string(filepath.Separator) {
		return "", fmt.Errorf("kernel install: invalid zip entry: %s", name)
	}
	if cleaned == ".." || strings.HasPrefix(cleaned, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("kernel install: zip entry escapes target: %s", name)
	}
	for _, seg := range strings.Split(filepath.ToSlash(cleaned), "/") {
		if seg == ".." {
			return "", fmt.Errorf("kernel install: zip entry escapes target: %s", name)
		}
	}

	absTarget, err := filepath.Abs(target)
	if err != nil {
		return "", err
	}
	dest := filepath.Join(absTarget, cleaned)
	absDest, err := filepath.Abs(dest)
	if err != nil {
		return "", err
	}
	relOut, err := filepath.Rel(absTarget, absDest)
	if err != nil {
		return "", err
	}
	if relOut == ".." || strings.HasPrefix(relOut, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("kernel install: zip entry escapes target: %s", name)
	}
	return absDest, nil
}

// windowsVolumePrefix reports drive-relative (C:evil) or UNC (//server/share) zip names.
func windowsVolumePrefix(slashName string) bool {
	if len(slashName) >= 2 && slashName[1] == ':' {
		c := slashName[0]
		if (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') {
			return true
		}
	}
	return strings.HasPrefix(slashName, "//")
}

type installItem struct {
	dest    string
	body    []byte
	prev    []byte
	existed bool
}

// Install extracts a kernel zip payload into target (overlay of .agents/.skills/.cursor/scripts).
// All entries are validated and buffered before any write. On write failure, newly created
// files are removed and overwritten files are restored to their prior contents.
func Install(target string, zipData []byte, opts InstallOptions) (int, error) {
	if len(zipData) == 0 {
		zipData = EmbeddedZip()
	}
	if len(zipData) == 0 {
		return 0, fmt.Errorf("empty kernel payload")
	}
	zr, err := zip.NewReader(bytes.NewReader(zipData), int64(len(zipData)))
	if err != nil {
		return 0, err
	}

	var plan []installItem
	for _, f := range zr.File {
		name := filepath.ToSlash(f.Name)
		if name == "" || strings.HasSuffix(name, "/") {
			continue
		}
		if name == "manifest.json" {
			name = ".arah/kernel.manifest.json"
		}
		dest, err := joinUnderTarget(target, name)
		if err != nil {
			return 0, err
		}
		item := installItem{dest: dest}
		fi, lerr := os.Lstat(dest)
		if lerr == nil {
			if fi.Mode()&os.ModeSymlink != 0 {
				return 0, fmt.Errorf("kernel install: refusing symlink destination: %s", name)
			}
			if !opts.Force {
				continue
			}
			prev, err := os.ReadFile(dest)
			if err != nil {
				return 0, err
			}
			item.prev = prev
			item.existed = true
		} else if !os.IsNotExist(lerr) {
			return 0, lerr
		}
		rc, err := f.Open()
		if err != nil {
			return 0, err
		}
		body, err := io.ReadAll(rc)
		_ = rc.Close()
		if err != nil {
			return 0, err
		}
		item.body = body
		plan = append(plan, item)
	}

	written := make([]installItem, 0, len(plan))
	rollback := func() {
		for i := len(written) - 1; i >= 0; i-- {
			w := written[i]
			if w.existed {
				_ = os.WriteFile(w.dest, w.prev, 0o644)
			} else {
				_ = os.Remove(w.dest)
			}
		}
	}
	for _, it := range plan {
		if err := os.MkdirAll(filepath.Dir(it.dest), 0o755); err != nil {
			rollback()
			return 0, err
		}
		if err := os.WriteFile(it.dest, it.body, 0o644); err != nil {
			rollback()
			return 0, err
		}
		written = append(written, it)
	}
	return len(written), nil
}
