package kernel

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	// PayloadZipRel is the go:embed input regenerated by Sync.
	PayloadZipRel = "internal/kernel/payload/kernel.zip"
)

func manifestBytes(m *Manifest) ([]byte, error) {
	raw, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(raw, '\n'), nil
}

// writePayloadZip builds a zip of allowlisted sources + manifest.json for go:embed.
func writePayloadZip(repoRoot string, entries []SourceEntry, m *Manifest) (string, error) {
	paths := make([]string, 0, len(entries)+1)
	for _, e := range entries {
		paths = append(paths, e.Dest)
	}
	paths = append(paths, "manifest.json")
	sort.Strings(paths)

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, rel := range paths {
		var raw []byte
		var err error
		if rel == "manifest.json" {
			raw, err = manifestBytes(m)
		} else {
			src := ""
			for _, e := range entries {
				if e.Dest == rel {
					src = filepath.Join(repoRoot, filepath.FromSlash(e.Source))
					break
				}
			}
			if src == "" {
				_ = zw.Close()
				return "", fmt.Errorf("payload: missing source for %s", rel)
			}
			raw, err = os.ReadFile(src)
		}
		if err != nil {
			_ = zw.Close()
			return "", err
		}
		w, err := zw.CreateHeader(&zip.FileHeader{
			Name:   rel,
			Method: zip.Deflate,
		})
		if err != nil {
			_ = zw.Close()
			return "", err
		}
		if _, err := w.Write(raw); err != nil {
			_ = zw.Close()
			return "", err
		}
	}
	if err := zw.Close(); err != nil {
		return "", err
	}

	out := filepath.Join(repoRoot, filepath.FromSlash(PayloadZipRel))
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(out, buf.Bytes(), 0o644); err != nil {
		return "", err
	}
	sum := sha256.Sum256(buf.Bytes())
	return hex.EncodeToString(sum[:]), nil
}

func verifyPayloadZip(repoRoot string, entries []SourceEntry, m *Manifest) []Drift {
	zipPath := filepath.Join(repoRoot, filepath.FromSlash(PayloadZipRel))
	raw, err := os.ReadFile(zipPath)
	if err != nil {
		return []Drift{{Path: PayloadZipRel, Reason: "missing embed payload zip"}}
	}
	return verifyZipBytes(raw, entries, m, PayloadZipRel)
}

func verifyZipBytes(raw []byte, entries []SourceEntry, m *Manifest, label string) []Drift {
	zr, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		return []Drift{{Path: label, Reason: "unreadable zip: " + err.Error()}}
	}
	want := map[string]string{}
	for _, e := range entries {
		want[e.Dest] = m.Files[e.Dest]
	}
	manRaw, err := manifestBytes(m)
	if err != nil {
		return []Drift{{Path: label, Reason: "manifest marshal failed"}}
	}
	h := sha256.Sum256(manRaw)
	want["manifest.json"] = hex.EncodeToString(h[:])

	var drifts []Drift
	seen := map[string]bool{}
	for _, f := range zr.File {
		name := filepath.ToSlash(f.Name)
		seen[name] = true
		rc, err := f.Open()
		if err != nil {
			drifts = append(drifts, Drift{Path: name, Reason: "zip entry unreadable"})
			continue
		}
		body, err := io.ReadAll(rc)
		_ = rc.Close()
		if err != nil {
			drifts = append(drifts, Drift{Path: name, Reason: "zip entry read failed"})
			continue
		}
		sum := sha256.Sum256(body)
		got := hex.EncodeToString(sum[:])
		exp, ok := want[name]
		if !ok {
			drifts = append(drifts, Drift{Path: name, Reason: "extra file in payload zip"})
			continue
		}
		if got != exp {
			drifts = append(drifts, Drift{Path: name, Reason: "payload zip digest mismatch", Want: shortDigest(exp), Got: shortDigest(got)})
		}
	}
	for name := range want {
		if !seen[name] {
			drifts = append(drifts, Drift{Path: name, Reason: "missing from payload zip"})
		}
	}
	sort.Slice(drifts, func(i, j int) bool { return drifts[i].Path < drifts[j].Path })
	return drifts
}

// InstallOptions controls kernel payload extraction into a consumer repo.
type InstallOptions struct {
	Force bool
}

// Install extracts a kernel zip payload into target (overlay of .agents/.skills/.cursor/scripts).
func Install(target string, zipData []byte, opts InstallOptions) (int, error) {
	if len(zipData) == 0 {
		zipData = EmbeddedZip()
	}
	if len(zipData) == 0 {
		return 0, fmt.Errorf("empty kernel payload")
	}
	zr, err := zip.NewReader(bytes.NewReader(zipData), int64(len(zipData)))
	if err != nil {
		return 0, err
	}
	installed := 0
	for _, f := range zr.File {
		name := filepath.ToSlash(f.Name)
		if name == "" || strings.HasSuffix(name, "/") {
			continue
		}
		if name == "manifest.json" {
			name = ".arah/kernel.manifest.json"
		}
		dest := filepath.Join(target, filepath.FromSlash(name))
		if !opts.Force {
			if _, err := os.Stat(dest); err == nil {
				continue
			}
		}
		rc, err := f.Open()
		if err != nil {
			return installed, err
		}
		body, err := io.ReadAll(rc)
		_ = rc.Close()
		if err != nil {
			return installed, err
		}
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return installed, err
		}
		if err := os.WriteFile(dest, body, 0o644); err != nil {
			return installed, err
		}
		installed++
	}
	return installed, nil
}
