#Requires -Version 5.1
<#
.SYNOPSIS
  Adapter opcional: Knowledge Graph do corpus via Graphify (complementar ao Agent Graph).
.DESCRIPTION
  Detecta o CLI `graphify` (PyPI: graphifyy). Default: extract --code-only (AST local,
  sem tokens). Sem CLI → exit 0 (skipped), salvo -Require.
  Escreve docs/_meta/knowledge-graph.manifest.yaml apontando a graphify-out/.
.EXAMPLE
  ./graphify-knowledge-graph.ps1
  ./graphify-knowledge-graph.ps1 -Mode status
  ./graphify-knowledge-graph.ps1 -Mode full -Require
  ./graphify-knowledge-graph.ps1 -DryRun
#>
param(
    [string]$Target = '',
    [ValidateSet('code-only', 'full', 'status')]
    [string]$Mode = 'code-only',
    [string]$Path = '.',
    [switch]$Require,
    [switch]$Force,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

if (-not $Target) {
    $Target = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '../..')).Path
} else {
    $Target = (Resolve-Path -LiteralPath $Target).Path
}

$MetaDir = Join-Path (Join-Path $Target 'docs') '_meta'
$ManifestPath = Join-Path $MetaDir 'knowledge-graph.manifest.yaml'
$OutDirRel = 'graphify-out'
$OutDir = Join-Path $Target $OutDirRel
$GraphRel = Join-Path $OutDirRel 'graph.json'
$ReportRel = Join-Path $OutDirRel 'GRAPH_REPORT.md'
$Sibling = 'docs/_meta/agent-graph.generated.json'

function Find-GraphifyCommand {
    $cmd = Get-Command graphify -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    # uv tool / pipx common locations are already on PATH when installed correctly
    return $null
}

function Write-Manifest {
    param(
        [string]$Status,
        [string]$EffectiveMode,
        [bool]$CliDetected,
        [string]$Notes
    )
    $ts = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    $cliFlag = if ($CliDetected) { 'true' } else { 'false' }
    $notesBlock = ($Notes -replace "`r`n", "`n") -replace "`n", "`n  "
    $yaml = @"
# Generated by graphify-knowledge-graph.ps1 — Knowledge Graph (corpus), not Agent Graph
version: 1
provider: graphify
provider_package: graphifyy
cli: graphify
mode: $EffectiveMode
status: $Status
generated_at: $ts
cli_detected: $cliFlag
sibling_of: $Sibling
artifacts:
  out_dir: $OutDirRel
  graph: $GraphRel
  report: $ReportRel
notes: |
  $notesBlock
"@
    if ($DryRun) {
        Write-Host "knowledge-graph: DryRun — would write $ManifestPath"
        Write-Host $yaml
        return
    }
    if (-not (Test-Path -LiteralPath $MetaDir)) {
        New-Item -ItemType Directory -Path $MetaDir -Force | Out-Null
    }
    Set-Content -LiteralPath $ManifestPath -Value $yaml -Encoding UTF8
    Write-Host "knowledge-graph: wrote $ManifestPath (status=$Status)"
}

$graphify = Find-GraphifyCommand
$cliOk = [bool]$graphify

if ($Mode -eq 'status') {
    $hasGraph = Test-Path -LiteralPath (Join-Path $Target $GraphRel)
    $status = if (-not $cliOk) { 'missing' } elseif ($hasGraph) { 'ready' } else { 'skipped' }
    $notes = if (-not $cliOk) {
        'CLI graphify not found. Install: uv tool install graphifyy  (or pipx install graphifyy). See docs/architecture/GRAPHIFY.md'
    } elseif ($hasGraph) {
        'CLI present; graphify-out/graph.json found.'
    } else {
        'CLI present; run arah knowledge-graph (code-only) to extract.'
    }
    Write-Manifest -Status $status -EffectiveMode 'status' -CliDetected $cliOk -Notes $notes
    if ($Require -and -not $cliOk) { exit 1 }
    exit 0
}

if (-not $cliOk) {
    $msg = 'CLI graphify not found — skipping Knowledge Graph. Install: uv tool install graphifyy. Docs: docs/architecture/GRAPHIFY.md'
    Write-Warning $msg
    Write-Manifest -Status 'missing' -EffectiveMode $Mode -CliDetected $false -Notes $msg
    if ($Require) {
        Write-Error 'knowledge-graph: -Require set but graphify CLI missing'
        exit 1
    }
    exit 0
}

if ($DryRun) {
    Write-Host "knowledge-graph: DryRun — would run: graphify extract $Path $(if ($Mode -eq 'code-only') { '--code-only' } else { '' })"
    Write-Manifest -Status 'skipped' -EffectiveMode $Mode -CliDetected $true -Notes 'DryRun — extract not executed'
    exit 0
}

$extractArgs = @('extract', $Path)
if ($Mode -eq 'code-only') { $extractArgs += '--code-only' }
if ($Force) { $extractArgs += '--force' }

Write-Host "knowledge-graph: $graphify $($extractArgs -join ' ')  (cwd=$Target)"
Push-Location $Target
try {
    & $graphify @extractArgs
    $exit = $LASTEXITCODE
} finally {
    Pop-Location
}

if ($null -ne $exit -and $exit -ne 0) {
    Write-Manifest -Status 'error' -EffectiveMode $Mode -CliDetected $true -Notes "graphify extract failed with exit $exit"
    if ($Require) { exit $exit }
    Write-Warning "knowledge-graph: extract failed (exit $exit) — continuing without hard fail"
    exit 0
}

$hasGraph = Test-Path -LiteralPath (Join-Path $Target $GraphRel)
$status = if ($hasGraph) { 'ready' } else { 'skipped' }
$notes = if ($hasGraph) {
    "Extract OK ($Mode). Query: graphify query `"…`" --graph graphify-out/graph.json. Distinct from Agent Graph ($Sibling)."
} else {
    "Extract finished but $GraphRel not found — check Graphify version/output layout."
}
Write-Manifest -Status $status -EffectiveMode $Mode -CliDetected $true -Notes $notes
exit 0
