#Requires -Version 5.1
<#
.SYNOPSIS
  Registra evento de agente na trilha de auditoria ARAH (append-only JSONL).
.EXAMPLE
  ./record-agent-event.ps1 -AgentId pr-steward -Action skill.invoke -Outcome ok
  ./record-agent-event.ps1 -AgentId release -Action release.cut -Outcome blocked -Blocked
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$AgentId,

    [Parameter(Mandatory = $true)]
    [string]$Action,

    [ValidateSet('ok', 'blocked', 'denied', 'error', 'pending')]
    [string]$Outcome = 'ok',

    [string]$AutonomyLevel = 'activate',
    [string]$Details = '',
    [string]$CorrelationId = '',
    [string]$HumanGate = '',
    [string]$Project = '',
    [switch]$Blocked
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..')
$AuditDir = Join-Path $RepoRoot '.arah\audit'
$AuditFile = Join-Path $AuditDir 'events.jsonl'
$ObsDir = Join-Path $RepoRoot '.arah\observability'
$SummaryFile = Join-Path $ObsDir 'summary.yaml'
$DiagFile = Join-Path $RepoRoot '.cursor\arah-live\diagnostics.jsonl'

if (-not $Project) {
    $cfgPath = Join-Path $RepoRoot 'arah.config.yaml'
    if (Test-Path $cfgPath) {
        $cfg = Get-Content $cfgPath -Raw
        if ($cfg -match '(?m)^\s*name:\s*(\S+)') { $Project = $Matches[1] }
    }
    if (-not $Project) { $Project = Split-Path $RepoRoot -Leaf }
}

New-Item -ItemType Directory -Path $AuditDir -Force | Out-Null
New-Item -ItemType Directory -Path $ObsDir -Force | Out-Null

if (-not $CorrelationId) {
    $CorrelationId = [guid]::NewGuid().ToString('N').Substring(0, 12)
}

$event = [ordered]@{
    ts = (Get-Date).ToUniversalTime().ToString('o')
    correlation_id = $CorrelationId
    project = $Project
    agent_id = $AgentId
    action = $Action
    autonomy_level = $AutonomyLevel
    outcome = if ($Blocked) { 'blocked' } else { $Outcome }
    human_gate = if ($HumanGate) { $HumanGate } else { $null }
    details = $Details
}

$line = ($event | ConvertTo-Json -Compress -Depth 5)
Add-Content -Path $AuditFile -Value $line -Encoding UTF8

$total = 0
if (Test-Path $SummaryFile) {
    $existing = Get-Content $SummaryFile -Raw
    if ($existing -match 'total_events:\s*(\d+)') { $total = [int]$Matches[1] }
}
$total++

$summary = @"
# Generated by record-agent-event.ps1 — do not edit manually
updated_at: $($event.ts)
project: $Project
total_events: $total
last_agent: $AgentId
last_action: $Action
last_outcome: $($event.outcome)
"@
Set-Content -Path $SummaryFile -Value $summary -Encoding UTF8

# Mirror to live diagnostics (fail-open)
try {
    $liveDir = Split-Path $DiagFile -Parent
    if (-not (Test-Path $liveDir)) { New-Item -ItemType Directory -Path $liveDir -Force | Out-Null }
    $diag = [ordered]@{
        ts = $event.ts
        level = if ($event.outcome -eq 'blocked') { 'warn' } else { 'info' }
        component = 'audit'
        message = "$AgentId → $Action ($($event.outcome))"
        detail = @{ correlation_id = $CorrelationId; project = $Project }
    }
    Add-Content -Path $DiagFile -Value ($diag | ConvertTo-Json -Compress) -Encoding UTF8
} catch { }

if (-not $Blocked) { Write-Verbose "Audit: $AuditFile" }
